-- Tabla Pacientes
CREATE TABLE Pacientes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dni VARCHAR 255 NOT NULL,
    nombre VARCHAR 255 NOT NULL,
    apellido VARCHAR 255 NOT NULL,
    email VARCHAR 255 NOT NULL,
    password VARCHAR 255 NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Turnos
CREATE TABLE Turnos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fecha VARCHAR 255 NOT NULL,
    hora VARCHAR 255 NOT NULL,
    pacienteId INTEGER NOT NULL,
    estado VARCHAR 255 NOT NULL DEFAULT 'reservado',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pacienteId) REFERENCES Pacientes(id)
);
